# opcode (https://github.com/DannyBen/opcode)

## Script Generation

build:
  op generate
  op man
#? Generate script and man pages

generate: bashly generate "$@"
#? Regenerate script

watch: op generate --watch
#? Watch files and regenerate script on change

## Testing

check:
  op shellcheck
  op shfmt
  op test
  green ALL CHECKS PASS

test: op unit-test && op acceptance-test
#? Run both unit tests and feature tests

unit-test: bats --recursive --print-output-on-failure --abort "${1:-test}"
#? Run all unit tests or a given test

acceptance-test: shellkin
#? Run feature tests

## Documentation

man: bashly render :mandoc doc && op man5 && op man-zip
#? Render the man pages
#? This is called automatically when running `op build`

man-zip: tar -czf ./tmp/manpages.tar.gz -C doc . && echo "saved tmp/manpages.tar.gz"
#? Create tmp/manpages.tar.gz

man-install: ssi install man doc
#? Install man pages locally


## Linting

shellcheck: shellcheck shellkin && green "PASS shellcheck"
#? Run shellcheck

shfmt: shfmt -ci -i 2 -d shellkin && green "PASS shfmt"
#? Run shfmt tests


private

man5:
  echo "generating 5-page man pages"
  pandoc -f markdown-smart -s --to man "doc/shellkin-stepdefs.md" > "doc/shellkin-stepdefs.5"
  pandoc -f markdown-smart -s --to man "doc/shellkin-feature.md" > "doc/shellkin-feature.5"
#? Generate the man5 (file format) documentation
