# opcode (https://github.com/DannyBen/opcode)

## Script Generation

generate: bashly generate "$@"
#? Regenerate script

watch: op generate --watch
#? Watch files and regenerate script on change

## Testing

test: bats --recursive --print-output-on-failure --abort "${1:-test}"
#? Run all unit tests or a given test

features: shellkin test
#? Run feature tests

## Documentation

man: bashly render :mandoc doc
#? Render the man pages

## Linting

shellcheck: shellcheck shellkin && green "PASS shellcheck"
#? Run shellcheck

shfmt: shfmt -ci -i 2 -d shellkin && green "PASS shfmt"
#? Run shfmt tests

