## Script Generation

generate: bashly generate "$@"
#? Regenerate script

watch: op generate --watch
#? Watch files and regenerate script on change

## Testing and Linting

test: bats --recursive --print-output-on-failure --abort "${1:-test}"
#? Run all tests or a given test

shellcheck: shellcheck shellkin && green "PASS shellcheck"
#? Run shellcheck

shfmt: shfmt -ci -i 2 -d shellkin && green "PASS shfmt"
#? Run shfmt tests

